create table Sensor(
id int generated by default as identity primary key,
"name" varchar (30) not null unique
);

create table Measurement (
id int generated by default as identity primary key,
value numeric(5,1) check (value>=-100 or value <=100) not null ,
raining boolean not null,
sensor_name varchar (30) references sensor ("name") on delete restrict,
created_at timestamp not null
);